version: "2.2"
services:
  server:
    build: .
    read_only: true
    cap_drop:
      - ALL
    tmpfs:
      - /tmp
    restart: always
    labels:
      traefik.enable: "true"
      traefik.protocol: "https"
      traefik.docker.network: "web"
      traefik.frontend.rule: "Host: grpc-fun.m.887.at"
      traefik.frontend.headers.customResponseHeaders: "X-Robots-Tag: noindex, nofollow, noarchive"
      traefik.port: "5001"
    networks:
      - web

networks:
  web:
    external: true

